Repository DependencyTrack/dependency-track, pull requests merged in 2022-07, with the labels that each got.

#1685 Add `CONTRIBUTING.md` and `DEVELOPING.md`
  .dockerignore
  .github/images/release-master.png
  .github/images/release-releasebranch.png
  .github/release-workflow.adoc
  .gitignore
  .run/Build API Server Image.run.xml
  .run/Build API Server.run.xml
  .run/Build Bundled Image.run.xml
  .run/Build Bundled.run.xml
  .run/Jetty.run.xml
  .run/Test.run.xml
  CONTRIBUTING.md
  DEVELOPING.md
  README.md
  RELEASING.md
  build-docs.sh
  dev-docs.sh
  docs/_config.yml
  pom.xml
  prerelease.sh
  release.sh
  scripts/dbschema-generate.datanucleus.properties
  scripts/dbschema-generate.log4j.properties
  scripts/dbschema-generate.sh
  scripts/docs-build.sh
  scripts/docs-dev.sh
  scripts/logs-clear.sh
  upgrade/3.0.0_to_3.0.1.sql
  upgrade/3.7.1_and_previous_maven_central_fix.sql
  upgrade/README.md
Labels: documentation

#1799 Feature/vulnerable software fuzzy matching
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/resources/v1/SearchResource.java
  src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
  src/main/java/org/dependencytrack/search/SearchManager.java
  src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/scanners/InternalAnalysisTask.java
  src/test/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManagerTest.java
Labels: enhancement

#1796 Add support for Prometheus metrics exposition
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/deploy-docker.md
  docs/_docs/getting-started/monitoring.md
  docs/files/grafana-dashboard.json
  docs/images/screenshots/monitoring-metrics-events.png
  docs/images/screenshots/monitoring-metrics-system.png
  src/main/docker/docker-compose.yml
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#1801 Bump Temurin base image to 11.0.15_10
  src/main/docker/Dockerfile
Labels: dependencies, docker

#1813 Use datastore-native limiting in queries where only a single result is desired
  src/main/java/org/dependencytrack/persistence/CacheQueryManager.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
Labels: enhancement

#1839 Add documentation for OSV datasource
  docs/_docs/datasources/internal-components.md
  docs/_docs/datasources/ossindex.md
  docs/_docs/datasources/osv.md
  docs/_docs/datasources/private-vuln-repo.md
  docs/_docs/datasources/repositories.md
  docs/_docs/datasources/routing.md
  docs/_docs/datasources/vulndb.md
  docs/images/osv-architecture.png
Labels: documentation
