Repository DependencyTrack/dependency-track, pull requests merged in 2022-12, with the labels that each got.

#2241 Revert "Bump actions/setup-java from 3.6.0 to 3.7.0"
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
Labels: dependencies, github_actions

#2230 chore: added swagger types for BOM operations
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomUploadResponse.java
  src/main/java/org/dependencytrack/resources/v1/vo/IsTokenBeingProcessedResponse.java
Labels: enhancement

#2242 Implement adding/deleting custom licenses via API
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
Labels: enhancement

#2227 Add commenter to `PROJECT_AUDIT_CHANGE` emails
  src/main/resources/templates/notification/publisher/email.peb
Labels: enhancement

#2244 Bump dependencies
  pom.xml
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
  src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
  src/main/java/org/dependencytrack/resources/v1/misc/Badger.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: dependencies, java

#2211 Example using DT
  docs/_docs/usage/executive-order-14028.md
  docs/_docs/usage/usecases.md
  docs/images/screenshots/API-key.png
Labels: documentation

#2256 grafana: add total heap size and 100% cpu lines
  docs/files/grafana-dashboard.json
Labels: documentation

#2258 Add Azure DevOps Extension to community integrations
  docs/_docs/integrations/community-integrations.md
Labels: documentation

#2240 Fix: Exact match between CPE with NA (-) update part
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskTest.java
Labels: defect

#2272 Display version status in `Audit Vulnerabilities` and `Exploit Predictions` tab
  docs/_docs/integrations/file-formats.md
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#2286 Bump Alpine to 2.2.0
  pom.xml
Labels: dependencies, java

#2288 doc: Adding forgotten IndexTask
  docs/_docs/getting-started/recurring-tasks.md
Labels: documentation

#2291 Bump temurin base image to 17.0.5_8
  src/main/docker/Dockerfile
Labels: dependencies, docker

#2296 Improve focusing on components in dependency graph
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: enhancement

#2276 Add changelog for 4.7.0
  RELEASING.md
  docs/_config.yml
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/database-support.md
  docs/_docs/getting-started/monitoring.md
  docs/_posts/2022-12-16-v4.7.0.md
  docs/images/screenshots/database-connection-pool-metrics.png
  src/main/resources/application.properties
Labels: documentation

#2299 Bump frontend to 4.7.0
  pom.xml
Labels: dependencies

#2302 Update release artifact hashes in 4.7.0 changelog
  .github/ISSUE_TEMPLATE/defect-report.yml
  docs/_posts/2022-12-16-v4.7.0.md
Labels: documentation

#2303 Port #2302 to `master`
  .github/ISSUE_TEMPLATE/defect-report.yml
  docs/_posts/2022-12-16-v4.7.0.md
Labels: documentation
