Repository DependencyTrack/dependency-track, pull requests merged in 2022-10, with the labels that each got.

#2007 Bugfix get test resource not working with whitespace in path
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/misc/BadgerTest.java
  src/test/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzerTest.java
  src/test/java/org/dependencytrack/util/HashUtilTest.java
Labels: enhancement

#1939 OSV fix : removed alias check
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/test/java/org/dependencytrack/task/OsvDownloadTaskTest.java
Labels: enhancement, vuln-aliases

#2022 Update container base images
  src/main/docker/Dockerfile
Labels: dependencies, docker

#2024 Update 4.6.0 changelog
  docs/_posts/2022-xx-xx-v4.6.0.md
Labels: documentation

#2011 Fix vulnerability aliases not being considered during metrics calculation
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/model/VulnerabilityAlias.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
Labels: vuln-aliases

#2031 Add pre-release and post-release checklists
  RELEASING.md
Labels: documentation

#2038 Update changelog for 4.6.0 release
  docs/_posts/2022-10-11-v4.6.0.md
Labels: documentation

#2037 Bump frontend to 4.6.0
  pom.xml
Labels: enhancement

#2040 Docker: Add optional EXTRA_JAVA_OPTIONS environment variable
  docs/_docs/getting-started/deploy-docker.md
  src/main/docker/Dockerfile
  src/main/docker/docker-compose.yml
Labels: enhancement

#2045 Update hashes for API server 4.6.1 release artifacts
  docs/_posts/2022-10-13-v4.6.1.md
Labels: documentation

#2060 ProposedSolution to Issue #2048
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
Labels: enhancement

#2068 Grafana: Use datasource for dropdown population
  docs/files/grafana-dashboard.json
Labels: documentation

#2071 Include SnykAnalysisTask thread pool in Prometheus metrics
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/deploy-docker.md
  docs/_docs/getting-started/monitoring.md
  src/main/docker/docker-compose.yml
  src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
  src/main/resources/application.properties
Labels: enhancement

#2077 Remove dependency on protobuf-java
  pom.xml
Labels: dependencies, java
