Repository DependencyTrack/dependency-track, pull requests merged in 2022-08, with the labels that each got.

#1845 Docs maintenance
  .github/dependabot.yml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-test.yaml
  DEVELOPING.md
  docs/Gemfile
  docs/_includes/anchor_headings.html
  docs/_layouts/default.html
  docs/_sass/_layout.scss
Labels: documentation

#1863 Add dev documentation for DataNucleus bytecode enhancement
  .run/DataNucleus Enhance.run.xml
  DEVELOPING.md
Labels: documentation

#1858 OSV - update ecosystems
  src/main/java/org/dependencytrack/parser/osv/model/Ecosystem.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
Labels: enhancement

#1804 Upgrade to Java 17
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  DEVELOPING.md
  pom.xml
  src/main/docker/Dockerfile
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/integration/ApiClient.java
Labels: enhancement, ci
