Repository DependencyTrack/dependency-track, pull requests merged in 2022-11, with the labels that each got.

#2140 Quick enhancement : add cacheable scan in Snyk analysis
  src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
Labels: enhancement

#1991 Migrate issue templates to issue forms
  .github/ISSUE_TEMPLATE/ask-a-question.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/defect-report.md
  .github/ISSUE_TEMPLATE/defect-report.yml
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/enhancement-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#2121 Refactoring in persistence
  src/main/java/org/dependencytrack/model/VulnerabilityAlias.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/test/java/org/dependencytrack/model/VulnerabilityAliasTest.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryFilterBuilderTest.java
Labels: enhancement

#2160 Switch to `jre17` distribution of `mssql-jdbc`
  pom.xml
Labels: dependencies, java

#2153 Create or delete new custom licenses using license API
  src/main/java/org/dependencytrack/model/License.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/test/java/org/dependencytrack/model/LicenseTest.java
  src/test/java/org/dependencytrack/resources/v1/LicenseResourceTest.java
Labels: enhancement

#2164 Update build artifact hashes for 4.6.3
  docs/_posts/2022-11-18-v4.6.3.md
Labels: documentation

#2185 feat: added google oidc
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation

#1977 1182: Add support for License URL
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/bom-1.xml
Labels: enhancement
