Repository DependencyTrack/dependency-track, pull requests merged in 2023-04, with the labels that each got.

#2631 fix project URL in mail & cisco webex
  src/main/resources/templates/notification/publisher/cswebex.peb
  src/main/resources/templates/notification/publisher/email.peb
Labels: defect

#2633 Add health endpoint
  docs/_docs/getting-started/monitoring.md
  src/main/docker/Dockerfile
  src/main/java/org/dependencytrack/health/HealthCheckInitializer.java
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#2668 Bump Alpine to 2.2.1
  pom.xml
Labels: dependencies, java

#2670 Allow for vulnerability alias synchronization to be disabled for each source that supports it
  docs/_docs/FAQ.md
  docs/_docs/datasources/github-advisories.md
  docs/_docs/datasources/ossindex.md
  docs/_docs/datasources/osv.md
  docs/_docs/datasources/snyk.md
  docs/images/osv-configuration.png
  docs/images/screenshots/github-advisories-configuration.png
  docs/images/screenshots/ossindex-configuration.png
  docs/images/screenshots/ossindex-conifguration.png
  docs/images/screenshots/osv-configuration.png
  docs/images/screenshots/snyk-configuration.png
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTaskTest.java
  src/test/java/org/dependencytrack/tasks/OsvDownloadTaskTest.java
  src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
Labels: enhancement, vuln-aliases

#2660 Fix migration of Jira config property group name
  src/main/java/org/dependencytrack/upgrade/v480/v480Updater.java
Labels: defect

#2575 Reduce heap usage during NVD mirroring
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
Labels: enhancement

#2678 Fix potential `Invalid state. Transaction has already started` in `RepositoryMetaAnalyzerTask`
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Labels: defect

#2659 Add changelog for v4.8.0
  docs/_posts/2023-04-18-v4.8.0.md
Labels: documentation

#2687 Bump frontend to v4.8.0
  pom.xml
Labels: enhancement

#2688 Bump version in docs
  docs/_config.yml
Labels: documentation

#2689 v4.8.0 post release
  .github/ISSUE_TEMPLATE/defect-report.yml
  docs/_posts/2023-04-18-v4.8.0.md
Labels: documentation

#2690 Port v4.8.0 post release
  .github/ISSUE_TEMPLATE/defect-report.yml
  docs/_posts/2023-04-18-v4.8.0.md
  pom.xml
Labels: documentation

#2691 Changelog Update 2023-04-18-v4.8.0.md
  docs/_posts/2023-04-18-v4.8.0.md
Labels: documentation

#2692 Update 2023-04-18-v4.8.0.md
  docs/_posts/2023-04-18-v4.8.0.md
Labels: documentation

#2697 repo meta analyzer: lower log level, do not swallow exception details
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Labels: enhancement
