Repository DependencyTrack/dependency-track, pull requests merged in 2023-08, with the labels that each got.

#2933 Add logging documentation and provide example Logback config for logging in JSON format
  .dockerignore
  docs/_docs/getting-started/deploy-docker.md
  docs/_docs/getting-started/monitoring.md
  src/main/docker/Dockerfile
  src/main/docker/docker-compose.yml
  src/main/docker/logback-json.xml
Labels: documentation

#2878 Fix VDR export containing non-vulnerable components
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#2400 Implement SPDX expressions
  docs/_docs/usage/policy-compliance.md
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpression.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpressionOperation.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxOperator.java
  src/main/java/org/dependencytrack/parser/spdx/expression/package-info.java
  src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/LicensePolicyEvaluator.java
  src/main/java/org/dependencytrack/upgrade/v490/v490Updater.java
  src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java
  src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
Labels: enhancement

#2989 feature: Adding proper logging to warn users when VEX data is not taken into account
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
Labels: enhancement
