Repository DependencyTrack/dependency-track, pull requests merged in 2023-07, with the labels that each got.

#2872 Fix memory leak issue in policy evaluation
  src/main/java/org/dependencytrack/policy/AbstractPolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/CpePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/VersionPolicyEvaluatorTest.java
Labels: defect

#2873 Fix memory leak issue in vex upload processing task
  src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
Labels: defect

#2651 Include Cloud SQL database connectors
  docs/_docs/getting-started/database-support.md
  pom.xml
Labels: enhancement

#2899 Add note about required subscription plan for Snyk
  docs/_docs/datasources/snyk.md
Labels: documentation

#2911 Update Snyk API version to `2023-06-22`
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v490/v490Updater.java
Labels: enhancement
