Repository DependencyTrack/dependency-track, pull requests merged in 2023-11, with the labels that each got.

#3167 guidance about 413 content to large
  docs/_docs/FAQ.md
Labels: documentation

#3154 Add retry with exponential backoff for NVD feed downloads
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
Labels: enhancement

#3171 Bump Alpine to `2.2.4-SNAPSHOT`
  pom.xml
Labels: dependencies, java

#3186 Improve OIDC documentation
  docs/_docs/getting-started/deploy-docker.md
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation

#2876 Support authentication for public / non-internal repositories
  src/main/java/org/dependencytrack/model/Repository.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
  src/test/java/org/dependencytrack/model/RepositoryTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
  src/test/java/org/dependencytrack/tasks/RepoMetaAnalysisTaskTest.java
Labels: enhancement

#3211 Improve logging for notification publishing
  docs/_docs/integrations/notifications.md
  docs/_posts/2023-xx-xx-v4.10.0.md
  src/main/java/org/dependencytrack/model/NotificationRule.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
  src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishers.java
  src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/PublishContext.java
  src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/ConsolePublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/CsWebexPublisherTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: enhancement

#3242 Bump `open-vulnerability-clients` to `5.0.3`
  pom.xml
Labels: dependencies, java

#3245 Tweak container health check to prevent `wget` zombie processes on slow hosts
  src/main/docker/Dockerfile
Labels: enhancement, docker

#3246 Fix NPEs in GitHub repository metadata analyzer
  docs/_docs/datasources/repositories.md
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Labels: defect
