Repository DependencyTrack/dependency-track, pull requests merged in 2023-06, with the labels that each got.

#2817 Fix GHA `set-output` deprecation warnings
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
Labels: ci

#2818 Bump Alpine to `2.2.3-SNAPSHOT`
  docs/_docs/getting-started/configuration.md
  pom.xml
  src/main/resources/application.properties
Labels: dependencies, java

#2769 Custom licenses
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
Labels: enhancement
