Repository DependencyTrack/dependency-track, pull requests merged in 2023-10, with the labels that each got.

#3067 Fix VEX export erroneously containing dependency graph
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect

#3068 Fix NPE in `doesProjectExist` when project version is `null`
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#3069 Bump temurin base image to `17.0.8.1_1`
  src/main/docker/Dockerfile
Labels: dependencies, docker

#3071 Update cyclonedx-core-java to 8.0.0
  pom.xml
Labels: dependencies, java

#3082 Fix `NugetMetaAnalyzerTest`
  src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Labels: defect

#3083 Fix wrong `latestVersion` being assigned to dependency graph entries without PURL
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/DependencyGraphResponse.java
  src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java
Labels: defect

#3102 Bump Cloud SQL connectors to `1.14.1`
  pom.xml
Labels: dependencies, java

#3076 Add changelog for 4.9.0 release
  docs/_config.yml
  docs/_posts/2023-10-16-v4.9.0.md
Labels: documentation

#3089 Use Java 21 JRE in container images
  src/main/docker/Dockerfile
Labels: enhancement

#3103 Pin digests of GitHub Actions
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lock.yaml
Labels: ci

#3104 Use strict token permissions in GitHub Actions workflows
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lock.yaml
Labels: ci

#3126 Backport: Fix impossible SQL query conditions causing DB indexes to be bypassed
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
Labels: defect

#3137 Bump `cyclonedx-core-java` to `8.0.3`
  pom.xml
Labels: defect, dependencies, java

#3141 Backport: Bump `cyclonedx-core-java` to `8.0.3`
  pom.xml
Labels: defect, dependencies, java

#3136 fixes(docs): outdated doc
  docs/_docs/datasources/github-advisories.md
Labels: documentation

#3153 Recommend `READ_COMMITTED_SNAPSHOT` isolation for MSSQL
  dev/docker-compose.mssql.yml
  docs/_docs/getting-started/database-support.md
Labels: documentation

#3143 Add changelog for v4.9.1
  docs/_posts/2023-10-30-v4.9.1.md
Labels: documentation

#3158 Port changelog for v4.9.1
  docs/_posts/2023-10-30-v4.9.1.md
Labels: documentation
