Repository DependencyTrack/dependency-track, pull requests merged in 2023-03, with the labels that each got.

#2547 Add developer docs for skipping NVD mirroring
  DEVELOPING.md
  scripts/data-nist-generate-dummy.sh
Labels: documentation

#2526 Execute `NistMirrorTask` and `EpssMirrorTask` on multi-threaded event service
  src/main/java/org/dependencytrack/event/EpssMirrorEvent.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/NistMirrorEvent.java
Labels: enhancement

#2525 Disable DataNucleus L2 cache for mirroring tasks
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/parser/epss/EpssParser.java
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
Labels: enhancement

#2586 Minor bugfix for PolicyEngine
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Labels: defect

#2563 Feature: Handle repository meta analyzers errors gracefully
  src/main/java/org/dependencytrack/exception/MetaAnalyzerException.java
  src/main/java/org/dependencytrack/tasks/repositories/CargoMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/GemMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/HexMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/PypiMetaAnalyzer.java
  src/main/java/org/dependencytrack/util/CacheStampedeBlocker.java
  src/test/java/org/dependencytrack/util/CacheStampedeBlockerTest.java
Labels: enhancement

#2592 Feature: Allow H2 web console usage for dev purposes
  .run/Jetty with H2 Console.run.xml
  pom.xml
  src/main/java/org/dependencytrack/persistence/H2WebConsoleInitializer.java
  src/main/webapp/WEB-INF/web.xml
  src/test/webapp/WEB-INF/h2-console-activation.xml
Labels: enhancement

#2561 Add developer docs for database inspection
  DEVELOPING.md
Labels: documentation

#2610 Fix: Move jira configuration
  src/main/java/org/dependencytrack/upgrade/v480/v480Updater.java
Labels: defect

#2626 Map Snyk publication time
  src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
  src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
Labels: enhancement
