Repository DependencyTrack/dependency-track, pull requests merged in 2023-02, with the labels that each got.

#2466 remove superfluous ComponentMetricsUpdate event dispatch
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
Labels: enhancement

#2467 Bom Upload: don't choke on removed project
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: enhancement

#2482 FIx link to contributing guidelines in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2483 DataNucleus: Add logging bridge
  pom.xml
Labels: enhancement, dependencies

#2481 Simplify and speed up VulnerabilityMetricsUpdateTask
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/model/VulnerabilityMetrics.java
  src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/YearMonthMetric.java
  src/test/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTaskTest.java
Labels: enhancement

#2527 Fix NPE in enabled OSV ecosystems computation
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
Labels: defect
