Repository DependencyTrack/dependency-track, pull requests merged in 2023-05, with the labels that each got.

#2724 Fixing broken link in DEVELOPING.md
  DEVELOPING.md
Labels: documentation

#2744 Bump Alpine to 2.2.2
  pom.xml
Labels: dependencies

#2750 Use `exec` to launch JVM process in container
  src/main/docker/Dockerfile
Labels: enhancement, docker
