Repository DependencyTrack/dependency-track, pull requests merged in 2023-01, with the labels that each got.

#2345 Docs: Github Advisories and fine-grained tokens
  docs/_docs/datasources/github-advisories.md
Labels: documentation

#2396 Fix: add user-agent header to Snyk requests
  src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/SnykAnalysisTaskTest.java
Labels: enhancement

#2403 Rename "Use Cases" docs to "Community Usage Examples"
  docs/_docs/usage/community-usage-examples.md
  docs/_docs/usage/executive-order-14028.md
  docs/_docs/usage/usecases.md
Labels: documentation

#2408 Include version of affected projects in Jira notification template
  src/main/resources/templates/notification/publisher/jira.peb
Labels: enhancement

#2418 Add Lift config and disable some noisy rules
  .lift.toml
Labels: ci

#2428 Fix vulndb column name in getVulnerabilityAliases method
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
Labels: defect

#2430 Fix Monitoring README
  docs/_docs/getting-started/monitoring.md
Labels: documentation

#2433 Update 4.7.1 release artifact checksums
  docs/_posts/2023-01-31-v4.7.1.md
Labels: documentation
