Repository DependencyTrack/dependency-track, pull requests merged in 2023-12, with the labels that each got.

#3257 Log status of NVD mirroring via REST API
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
Labels: enhancement

#3276 Honour proxy settings when mirroring CVEs via NVD REST API
  pom.xml
  src/main/java/org/dependencytrack/common/AlpineHttpProxySelector.java
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/test/java/org/dependencytrack/common/AlpineHttpProxySelectorTest.java
Labels: enhancement

#3254 Add changelog for v4.10
  docs/_config.yml
  docs/_docs/getting-started/monitoring.md
  docs/_posts/2023-12-06-v4.10.0.md
  docs/_posts/2023-xx-xx-v4.10.0.md
Labels: documentation

#3281 Bump Alpine to 2.2.4
  pom.xml
Labels: dependencies, java

#3260 Return processing token when cloning project #2842
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#3304 Fix dropping of `CWE` table failing due to FK constraint
  src/main/java/org/dependencytrack/upgrade/v4110/v4110Updater.java
Labels: defect

#3305 Fix notifications not being sent for child projects where `active` is `null`
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: defect

#3306 Backport: Fix notifications not being sent for child projects where `active` is `null`
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: defect

#3307 Fix NPE in `VersionDistancePolicyEvaluator` when project has no direct dependencies
  src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java
Labels: defect

#3308 Backport: Fix NPE in VersionDistancePolicyEvaluator when project has no direct dependencies
  src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java
Labels: defect

#3300 Fix GitHub purl example in v4.10.0 changelog
  docs/_posts/2023-12-08-v4.10.0.md
Labels: documentation

#3311 Fix `ClassCastException` when updating an existing `ProjectMetadata#authors` field
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3312 Backport: Fix `ClassCastException` when updating an existing `ProjectMetadata#authors` field
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3313 feat: Improve Error handling and add default version type
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Labels: defect

#3322 Fix NVD API's last modified timestamp requiring restart to be applied
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
Labels: defect

#3323 Backport: Fix NVD API's last modified timestamp requiring restart to be applied
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
Labels: defect

#3315 Backport: Improve Error handling and add default version type
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Labels: defect

#3327 Add changelog for v4.10.1
  docs/_posts/2023-12-19-v4.10.1.md
Labels: documentation
