Repository DependencyTrack/dependency-track, pull requests merged in 2024-02, with the labels that each got.

#3425 feat(vulnerabilities): enhance API to support frontend changes for active/inactive affected projects
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/AffectedProject.java
Labels: enhancement

#3437 Fix VulnDB parser being unable to import vulnerability records when 'nvd_additional_information' is empty
  src/main/java/org/dependencytrack/parser/vulndb/VulnDbParser.java
Labels: defect, integration/vulndb

#3422 Subject prefix
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: enhancement

#3456 Fix `URISyntaxException` when NPM PURL contains special characters
  src/main/java/org/dependencytrack/tasks/repositories/AbstractMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/NpmMetaAnalyzerTest.java
Labels: defect

#3275 Webhook alert token and new user alerts
  docs/_docs/integrations/notifications.md
  src/main/java/org/dependencytrack/notification/NotificationConstants.java
  src/main/java/org/dependencytrack/notification/NotificationGroup.java
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
Labels: enhancement

#2472 Global Audit View: Vulnerabilities
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/test/java/org/dependencytrack/model/GroupedFindingTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#3487 Bump various dependencies
  pom.xml
Labels: dependencies, java

#3488 Finding Attributed On date is not retained when cloning projects
  dev/scripts/data-nist-generate-dummy.sh
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Labels: defect

#3357 Refactor BOM upload processing for better efficiency, correctness, and consistency
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/docker/logback.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/event/BomUploadEvent.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentIdentity.java
  src/main/java/org/dependencytrack/model/License.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/listener/IndexingInstanceLifecycleListener.java
  src/main/java/org/dependencytrack/persistence/listener/L2CacheEvictingInstanceLifecycleListener.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentificationUtil.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentifier.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/main/resources/logback.xml
  src/test/java/org/dependencytrack/event/BomUploadEventTest.java
  src/test/java/org/dependencytrack/model/ComponentIdentityTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/util/InternalComponentIdentificationUtilTest.java
  src/test/java/org/dependencytrack/util/PersistenceUtilTest.java
  src/test/resources/bom-1.xml
  src/test/resources/unit/bom-1.xml
  src/test/resources/unit/bom-custom-license.json
  src/test/resources/unit/bom-empty.json
  src/test/resources/unit/bom-issue1905.json
  src/test/resources/unit/bom-issue2519.xml
  src/test/resources/unit/bom-issue3371.json
  src/test/resources/unit/bom-metadata-components.json
  src/test/resources/unit/bom-service.json
Labels: enhancement, performance

#3491 Bump CWE dictionary to v4.13
  dev/scripts/cwe-dictionary-generate.py
  src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: enhancement

#3492 Apply consistent formatting to SQL queries; Use text blocks instead of string concatenation
  src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/test/java/org/dependencytrack/model/FindingTest.java
  src/test/java/org/dependencytrack/model/GroupedFindingTest.java
Labels: enhancement

#3494 Align retry configuration and behavior across analyzers
  dev/monitoring/grafana/dashboards/apiserver.json
  docs/_posts/2024-xx-xx-v4.11.0.md
  docs/files/grafana-dashboard.json
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/scanners/SnykAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/main/java/org/dependencytrack/util/RetryUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
Labels: enhancement

#3493 Improve test coverage of Trivy integration
  pom.xml
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/parser/trivy/TrivyParser.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: integration/trivy

#3490 Adds NVD disclaimer at the top of the documentation page for NVD.
  docs/_docs/datasources/nvd.md
Labels: documentation

#3502 Add auto-generated changelog to GitHub releases
  .github/release.yml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
Labels: enhancement

#3514 Report test coverage for all branches, not just `master`
  .github/workflows/ci-test.yaml
Labels: ci
