Repository DependencyTrack/dependency-track, pull requests merged in 2024-10, with the labels that each got.

#4201 Fix: Unauthorized access to projects over /vulnerability/{source}/vuln/{vuln}(/projects) when ACL is enabled
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#4202 Fix redundant `ConfigProperty` queries in `BadgeResource`
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
Labels: enhancement

#4203 Fix potential race condition in `PolicyEngineTest#notificationTest`
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Labels: technical debt

#4205 Fix `getAffectedProjectACLDisabledTest` flakiness
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: technical debt

#4204 Bump mysql-connector-j to 8.2.0
  pom.xml
Labels: dependencies

#4208 Fix `affectedComponents` getting removed when updating an internal vulnerability
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/tasks/AbstractNistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#4209 Bump bundled frontend to 4.12.0
  pom.xml
Labels: dependencies

#4186 Update changelog for v4.12.0 with recent changes
  docs/_docs/integrations/badges.md
  docs/_posts/2024-10-01-v4.12.0.md
Labels: documentation

#4216 Prevent duplicate policy violations
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/util/LockUtil.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Labels: defect, backport/4.12.1

#4221 Fix unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling
  src/main/resources/application.properties
Labels: defect, backport/4.12.1

#4232 Backport: Fix logs not containing usernames of deleted users
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: defect

#4233 Backport: Fix unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling
  src/main/resources/application.properties
Labels: defect

#4234 Backport: Prevent duplicate policy violations
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/util/LockUtil.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Labels: defect

#4231 Enhance policy violation de-duplication logic
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Labels: defect, backport/4.12.1

#4235 Backport: Enhance policy violation de-duplication logic
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
Labels: defect

#4245 Fix inaccuracies of Trivy analyzer
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect, backport/4.12.1

#4246 Fix redundant query for "ignore unfixed" config during Trivy analysis
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
Labels: defect, backport/4.12.1

#4258 Backport: Fix inaccuracies of Trivy analyzer
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect

#4259 Backport: Fix redundant query for "ignore unfixed" config during Trivy analysis
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
Labels: defect

#4271 Backport: Bump cyclonedx-core-java to 9.1.0
  pom.xml
Labels: dependencies

#4276 Update Deploying Docker guide to Compose v2
  docs/_docs/getting-started/deploy-docker.md
  src/main/docker/docker-compose.yml
Labels: documentation

#4304 Provide support for AWS JDBC Driver
  pom.xml
Labels: enhancement

#4308 Bump Alpine to 3.1.1
  pom.xml
Labels: dependencies, backport/4.12.1

#4309 Backport: Bump Alpine to 3.1.1
  pom.xml
Labels: dependencies

#4310 Disable DataNucleus L2 cache globally
  src/main/java/org/dependencytrack/parser/epss/EpssParser.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/listener/L2CacheEvictingInstanceLifecycleListener.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/util/PersistenceUtilTest.java
Labels: technical debt

#4312 Restrict max heap size of `Jetty` run config to 2GB
  .idea/runConfigurations/Jetty.run.xml
Labels: dx

#4314 Bump Temurin base image to 21.0.5_11
  src/main/docker/Dockerfile
Labels: dependencies, backport/4.12.1

#4315 Backport: Bump Temurin base image to 21.0.5_11
  src/main/docker/Dockerfile
Labels: dependencies

#4311 Fix excessive memory usage of portfolio repository meta analysis
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Labels: defect, backport/4.12.1

#4317 Backport: Fix excessive memory usage of portfolio repository meta analysis
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
Labels: defect

#4319 Backport: Bump bundled frontend to 4.12.1
  pom.xml
Labels: dependencies

#4318 Bump bundled frontend to 4.12.1
  pom.xml
Labels: dependencies, backport/4.12.1

#4280 Add changelog for v4.12.1
  docs/_posts/2024-10-25-v4.12.1.md
Labels: documentation

#4273 Add property to control `verified` flag in DefectDojo integration
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
  src/main/resources/application.properties
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#4325 Reduce memory usage of metrics update tasks
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Labels: enhancement, backport/4.12.2

#4326 Fix nullable metrics fields having getters of primitive type
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
Labels: defect, backport/4.12.2

#4339 Fix CPE matching logic for NVD Rest
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
  src/test/resources/unit/nvd/api/jsons/cve-2024-23113.json
Labels: defect, backport/4.12.2
