Repository DependencyTrack/dependency-track, pull requests merged in 2024-05, with the labels that each got.

#3661 Fall back to no authentication when OSS Index API token decryption fails
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
Labels: enhancement, integration/ossindex

#3662 Truncate `ComponentProperty` value at 1024 characters
  src/main/java/org/dependencytrack/model/ComponentProperty.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-1.xml
Labels: enhancement

#3664 Fix unique constraint violation during NVD mirroring via feed files
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/servlets/NvdMirrorServlet.java
  src/main/java/org/dependencytrack/tasks/AbstractNistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.json
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.meta
Labels: defect

#3667 De-duplicate CPEs in NVD feed file parsing
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2021_duplicate-cpes.json
Labels: defect

#3668 Start Jersey `TestContainer` once per class vs. once per test method
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/JerseyTestRule.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/IntegrationResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/LdapResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/LicenseResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/OidcResourceAuthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/OidcResourceUnauthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/SearchResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceUnauthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ViolationAnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/exception/ClientErrorExceptionMapperTest.java
  src/test/java/org/dependencytrack/resources/v1/exception/ConstraintViolationExceptionMapperTest.java
Labels: dx

#3666 Add the project name and project URL to bom processing notifications
  src/main/resources/templates/notification/publisher/msteams.peb
  src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
Labels: enhancement, integration/msteams

#3672 Run builds and CI on `feature-*` branches
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-test.yaml
  DEVELOPING.md
Labels: dx

#3674 Bump dependencies to their latest version
  pom.xml
Labels: dependencies, java

#3677 Disable Maven transfer progress in CI
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
Labels: dx

#3679 Fix changelog typo; Set release date; Bump docs version
  docs/_config.yml
  docs/_posts/2024-05-07-v4.11.0.md
Labels: documentation

#3678 Fix missing default repos for Hackage and Nixpkgs
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
Labels: defect

#3680 Reduce verbosity of `ResourceTest`s
  pom.xml
  src/test/resources/logging.properties
Labels: dx

#3681 Bump bundled frontend to v4.11.0
  DEVELOPING.md
  docs/_posts/2024-05-07-v4.11.0.md
  pom.xml
Labels: enhancement

#3682 Raise baseline Java version to 21
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  DEVELOPING.md
  docs/_posts/2024-xx-xx-v4.12.0.md
  pom.xml
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/test/java/org/dependencytrack/common/ManagedHttpClientFactoryTest.java
Labels: enhancement

#3675 Bump Alpine to `2.2.6-SNAPSHOT`
  .github/ISSUE_TEMPLATE/defect-report.yml
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  DEVELOPING.md
  docs/_config.yml
  docs/_posts/2024-05-07-v4.11.0.md
  docs/_posts/2024-xx-xx-v4.12.0.md
  pom.xml
  src/main/java/org/dependencytrack/model/ProjectProperty.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/tasks/AbstractNistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/tasks/NistApiMirrorTask.java
  src/main/resources/logback.xml
  src/test/java/org/dependencytrack/common/ManagedHttpClientFactoryTest.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTaskTest.java
  src/test/java/org/dependencytrack/tasks/OsvDownloadTaskTest.java
  src/test/resources/logging.properties
Labels: dependencies, java

#3691 Add active Field To Project Versions
  src/main/java/org/dependencytrack/model/ProjectVersion.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#3697 Fix failing JSON BOM validation when `specVersion` is not one of the first fields
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3698 Backport: Fix failing JSON BOM validation when `specVersion` is not one of the first fields
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3700 Fix broken global vuln audit view for MSSQL
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
Labels: defect

#3701 Backport: Fix broken global vuln audit view for MSSQL
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
Labels: defect

#3710 Support ingestion of CycloneDX v1.6 BOMs
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporterTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/resources/unit/cyclonedx/valid-bom-1.0.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.1.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.2.json
  src/test/resources/unit/cyclonedx/valid-bom-1.2.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.3.json
  src/test/resources/unit/cyclonedx/valid-bom-1.3.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.4.json
  src/test/resources/unit/cyclonedx/valid-bom-1.4.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.5.json
  src/test/resources/unit/cyclonedx/valid-bom-1.5.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.6.json
  src/test/resources/unit/cyclonedx/valid-bom-1.6.xml
Labels: enhancement, cdx-1.6

#3712 Update database support docs
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/database-support.md
  src/main/resources/application.properties
Labels: documentation

#3714 Fix compiler warnings
  pom.xml
  src/main/java/org/dependencytrack/common/ManagedHttpClientFactory.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
  src/main/java/org/dependencytrack/integrations/fortifyssc/FortifySscUploader.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/vulndb/VulnDbParser.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Results.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/search/IndexManager.java
  src/main/java/org/dependencytrack/tasks/EpssMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
  src/test/java/org/dependencytrack/integrations/fortifyssc/FortifySscClientTest.java
  src/test/java/org/dependencytrack/model/VulnerabilityMetricsTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporterTest.java
  src/test/java/org/dependencytrack/parser/vulndb/ModelConverterTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
  src/test/java/org/dependencytrack/tasks/scanners/VulnDBAnalysisTaskTest.java
Labels: technical debt

#3722 Remove legacy `BomUploadProcessingTask`
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: technical debt

#3726 Migrate from Swagger v2 to OpenAPI v3
  pom.xml
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
  src/main/java/org/dependencytrack/resources/OpenApiResource.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/CweResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/SearchResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
  src/main/java/org/dependencytrack/resources/v1/problems/InvalidBomProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomUploadResponse.java
  src/main/java/org/dependencytrack/resources/v1/vo/IsTokenBeingProcessedResponse.java
  src/main/webapp/WEB-INF/openapi-configuration.yaml
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement, breaking change, api docs

#3727 fix os handling when trivy sets pkgType on properties
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy

#3729 Backport: fix os handling when trivy sets pkgType on properties
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy

#3728 Improve OpenAPI v3 integration
  pom.xml
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/CweResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/SearchResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/resources/openapi-configuration.yaml
  src/main/webapp/WEB-INF/openapi-configuration.yaml
  src/test/java/org/dependencytrack/resources/OpenApiResourceTest.java
Labels: enhancement, api docs

#3731 Fix OpenAPI types of UNIX timestamp fields
  src/main/java/org/dependencytrack/model/AffectedVersionAttribution.java
  src/main/java/org/dependencytrack/model/AnalysisComment.java
  src/main/java/org/dependencytrack/model/Bom.java
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/FindingAttribution.java
  src/main/java/org/dependencytrack/model/PolicyViolation.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
  src/main/java/org/dependencytrack/model/RepositoryMetaComponent.java
  src/main/java/org/dependencytrack/model/Vex.java
  src/main/java/org/dependencytrack/model/ViolationAnalysisComment.java
  src/main/java/org/dependencytrack/model/VulnerabilityMetrics.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/vo/IsTokenBeingProcessedResponse.java
Labels: defect, api docs

#3733 Add changelog for v4.11.1 and bump bundled frontend
  docs/_posts/2024-05-19-v4.11.1.md
  pom.xml
Labels: documentation

#3736 Add date format to support offset in nuget analyser
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Labels: enhancement

#3745 Fix project name not showing in Jira tickets
  src/main/resources/templates/notification/publisher/jira.peb
Labels: defect, integration/jira

#3746 Add EPSS conditions to policies
  src/main/java/org/dependencytrack/model/PolicyCondition.java
  src/main/java/org/dependencytrack/policy/EpssPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/test/java/org/dependencytrack/policy/EpssPolicyEvaluatorTest.java
Labels: enhancement

#3761 Search component by group
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: enhancement

#3770 Fix `jakarta.servlet-api` not being inherited from `alpine-server`
  pom.xml
Labels: defect

#3782 Fix licenses not being resolved by name
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect
