Repository DependencyTrack/dependency-track, pull requests merged in 2024-06, with the labels that each got.

#3785 Backport: Handle breaking change in Trivy server API
  src/main/java/org/dependencytrack/parser/trivy/model/Application.java
  src/main/java/org/dependencytrack/parser/trivy/model/Library.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect

#3787 Backport: Fix project name not showing in Jira tickets
  src/main/resources/templates/notification/publisher/jira.peb
Labels: defect

#3788 Backport: Add date format to support offset in NuGet timestamps
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Labels: defect

#3789 Update database support docs
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/database-support.md
  src/main/resources/application.properties
Labels: documentation

#3786 Backport: Fix licenses not being resolved by name
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3791 Fix Slack notifications failing when no base URL is configured
  src/main/resources/templates/notification/publisher/slack.peb
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
Labels: defect

#3792 Backport: Fix Slack notifications failing when no base URL is configured
  src/main/resources/templates/notification/publisher/slack.peb
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
Labels: defect

#3793 Bump bundled frontend to 4.11.2
  pom.xml
Labels: dependencies

#3794 Backport: Bump bundled frontend to 4.11.2
  pom.xml
Labels: dependencies

#3790 Add changelog for v4.11.2
  docs/_posts/2024-06-02-v4.11.2.md
Labels: documentation

#3796 Add Notification For `BOM_VALIDATION_FAILED`
  docs/_docs/integrations/notifications.md
  src/main/java/org/dependencytrack/notification/NotificationConstants.java
  src/main/java/org/dependencytrack/notification/NotificationGroup.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/main/java/org/dependencytrack/notification/publisher/Publisher.java
  src/main/java/org/dependencytrack/notification/vo/BomValidationFailed.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/main/resources/templates/notification/publisher/email.peb
  src/main/resources/templates/notification/publisher/msteams.peb
  src/main/resources/templates/notification/publisher/slack.peb
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/JiraPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MattermostPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/MsTeamsPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SlackPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/WebhookPublisherTest.java
Labels: enhancement

#3801 Fix `JDODataStoreException` for unresolved licenses during BOM upload processing
  docs/_posts/2024-06-03-v4.11.3.md
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3803 Creating ADOPTERS.md as well as ADOPTERS ISSUE Type for future adopters showcase
  .github/ISSUE_TEMPLATE/adopt-dependency-track.yaml
  ADOPTERS.md
Labels: documentation

#3805 Issue-3769 : fix update component external references
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: defect

#3819 Bump CWE dictionary to v4.14
  dev/scripts/cwe-dictionary-generate.py
  src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: enhancement

#3839 vulnerabilityAudit incorrectly displaying non-active projects
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
Labels: defect

#3847 Bump `cyclonedx-core-java` to `9.0.2`
  pom.xml
Labels: dependencies, java

#3843 feat: autocreate project with tags
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: enhancement

#3863 Backport: Support ingestion of CycloneDX v1.6 BOMs
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporterTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/resources/unit/cyclonedx/valid-bom-1.0.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.1.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.2.json
  src/test/resources/unit/cyclonedx/valid-bom-1.2.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.3.json
  src/test/resources/unit/cyclonedx/valid-bom-1.3.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.4.json
  src/test/resources/unit/cyclonedx/valid-bom-1.4.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.5.json
  src/test/resources/unit/cyclonedx/valid-bom-1.5.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.6.json
  src/test/resources/unit/cyclonedx/valid-bom-1.6.xml
Labels: enhancement, cdx-1.6

#3864 Backport: Fix inverted "show inactive" filter in vulnerability audit view
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
Labels: defect

#3865 Fix BOM validation failing when URL contains encoded `[` and `]` characters
  pom.xml
  src/main/java/org/dependencytrack/util/XmlUtil.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3866 Backport: Fix BOM validation failing when URL contains encoded `[` and `]` characters
  pom.xml
  src/main/java/org/dependencytrack/util/XmlUtil.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3867 Backport: Fix external references not being updated via `POST /v1/component`
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: defect

#3870 Prevent XXE injection during CycloneDX validation and parsing
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3871 Backport: Prevent XXE injection during CycloneDX validation and parsing
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
Labels: defect

#3869 Improve performance of findings retrieval
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/VulnIdAndSource.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/util/PurlUtil.java
Labels: enhancement, performance

#3874 Bump bundled frontend to 4.11.4
  pom.xml
Labels: dependencies

#3875 Backport: Bump bundled frontend to 4.11.4
  pom.xml
Labels: dependencies

#3868 Add changelog for v4.11.4
  docs/_posts/2024-06-24-v4.11.4.md
Labels: documentation

#3877 Fix `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3881 Add REST endpoints for tag retrieval
  src/main/java/org/dependencytrack/model/validation/LowerCase.java
  src/main/java/org/dependencytrack/model/validation/LowerCaseValidator.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/TagListResponseItem.java
  src/main/java/org/dependencytrack/resources/v1/vo/TaggedPolicyListResponseItem.java
  src/main/java/org/dependencytrack/resources/v1/vo/TaggedProjectListResponseItem.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement

#3887 Deprecate `/api/v1/tag/{policyUuid}` in favor of `/api/v1/tag/policy/{uuid}`
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement

#3888 Relax lowercase requirement for `/api/v1/tag/{name}/project` and `/api/v1/tag/{name}/policy`
  src/main/java/org/dependencytrack/model/validation/LowerCase.java
  src/main/java/org/dependencytrack/model/validation/LowerCaseValidator.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: defect

#3889 Fix NPE when querying component metadata for projects without findings
  src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: defect

#3893 Enable string de-duplication JVM option per default
  .idea/runConfigurations/Jetty with H2 Console.run.xml
  .idea/runConfigurations/Jetty.run.xml
  src/main/docker/Dockerfile
Labels: enhancement, performance

#3894 Add REST endpoints for bulk tagging & un-tagging of projects
  src/main/java/org/dependencytrack/model/validation/ValidUuid.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement

#3896 Add REST endpoint for tag deletion
  src/main/java/org/dependencytrack/auth/Permissions.java
  src/main/java/org/dependencytrack/exception/TagOperationFailedException.java
  src/main/java/org/dependencytrack/model/Policy.java
  src/main/java/org/dependencytrack/model/Tag.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/TagOperationProblemDetails.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/auth/PermissionsTest.java
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement
