Repository DependencyTrack/dependency-track, pull requests merged in 2024-01, with the labels that each got.

#3347 Updated terminology.md to describe the Risk Score calculation
  docs/_docs/terminology.md
Labels: documentation

#3386 docs: fix build status badge
  README.md
Labels: documentation

#3394 Ignore withdrawn Github advisories
  src/main/java/org/dependencytrack/parser/github/graphql/GitHubSecurityAdvisoryParser.java
  src/test/java/org/dependencytrack/parser/github/GitHubSecurityAdvisoryParserTest.java
  src/test/resources/unit/github.jsons/GHSA-8v27-2fg9-7h62.json
Labels: defect

#3408 Store computed severities in the database
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
  src/main/java/org/dependencytrack/upgrade/v4110/v4110Updater.java
  src/test/java/org/dependencytrack/model/VulnerabilityTest.java
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
Labels: enhancement

#3414 docs(azure-ad): large enterprise group configuration
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation

#3411 Fix image link on openidconnect-configuration.md
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation

#3417 Bump Alpine to `2.2.5-SNAPSHOT`
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/openidconnect-configuration.md
  pom.xml
  src/main/resources/application.properties
Labels: dependencies, java
