Repository DependencyTrack/dependency-track, pull requests merged in 2024-08, with the labels that each got.

#4026 Fix project link for new vulnerable dependency for email
  src/main/resources/templates/notification/publisher/email.peb
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: defect

#4032 Update changelog for v4.12.0 with recent changes
  docs/_docs/integrations/rest-api.md
  docs/_posts/2024-xx-xx-v4.12.0.md
  docs/images/screenshots/swagger-ui-console.png
  docs/images/screenshots/teams.png
Labels: documentation

#4040 Backport: Handle breaking change in Trivy v0.54.0 server API
  src/main/java/org/dependencytrack/parser/trivy/model/Options.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect

#4043 Backport: Fix anchors in changelog documenation
  docs/_layouts/default.html
  docs/_posts/2018-03-30-v3.0.2.md
  docs/_posts/2018-10-02-v3.2.2.md
  docs/_posts/2018-10-25-v3.3.0.md
  docs/_posts/2018-11-13-v3.3.1.md
  docs/_posts/2018-12-22-v3.4.0.md
  docs/_posts/2019-04-16-v3.4.1.md
  docs/_posts/2019-06-07-v3.5.0.md
  docs/_posts/2019-07-17-v3.5.1.md
  docs/_posts/2019-09-28-v3.6.0.md
  docs/_posts/2019-10-01-v3.6.1.md
  docs/_posts/2019-12-16-v3.7.0.md
  docs/_posts/2020-01-07-v3.7.1.md
  docs/_posts/2020-03-22-v3.8.0.md
  docs/_posts/2021-01-03-v4.0.0.md
  docs/_posts/2021-01-12-v4.0.1.md
  docs/_posts/2021-02-09-v4.1.0.md
  docs/_posts/2021-03-17-v4.2.0.md
  docs/_posts/2021-03-20-v4.2.1.md
  docs/_posts/2021-05-07-v4.2.2.md
  docs/_posts/2021-08-02-v4.3.0.md
  docs/_posts/2021-08-03-v4.3.1.md
  docs/_posts/2021-08-07-v4.3.2.md
  docs/_posts/2021-08-20-v4.3.3.md
  docs/_posts/2021-08-31-v4.3.4.md
  docs/_posts/2021-09-20-v4.3.5.md
  docs/_posts/2021-09-20-v4.3.6.md
  docs/_posts/2022-02-17-v4.4.0.md
  docs/_posts/2022-02-18-v4.4.1.md
  docs/_posts/2022-03-04-v4.4.2.md
  docs/_posts/2022-05-18-v4.5.0.md
  docs/_posts/2022-10-11-v4.6.0.md
  docs/_posts/2022-10-13-v4.6.1.md
  docs/_posts/2022-10-24-v4.6.2.md
  docs/_posts/2022-11-18-v4.6.3.md
  docs/_posts/2022-12-16-v4.7.0.md
  docs/_posts/2023-01-31-v4.7.1.md
  docs/_posts/2023-04-18-v4.8.0.md
  docs/_posts/2023-05-16-v4.8.1.md
  docs/_posts/2023-05-17-v4.8.2.md
  docs/_posts/2023-10-16-v4.9.0.md
  docs/_posts/2023-10-30-v4.9.1.md
  docs/_posts/2023-12-08-v4.10.0.md
  docs/_posts/2023-12-19-v4.10.1.md
  docs/_posts/2024-05-07-v4.11.0.md
  docs/_posts/2024-05-19-v4.11.1.md
  docs/_posts/2024-06-01-v4.11.2.md
  docs/_posts/2024-06-03-v4.11.3.md
  docs/_posts/2024-06-24-v4.11.4.md
  docs/_posts/2024-07-08-v4.11.5.md
Labels: defect, documentation

#4041 Backport: Fix validation error when XML BOM declares multiple namespaces
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/resources/unit/bom-issue4008.xml
Labels: defect

#4044 Backport: Fix project link for new vulnerable dependency for email
  src/main/resources/templates/notification/publisher/email.peb
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: defect

#4042 Backport: Fix `JDOUserException` when multiple licenses match a component's license name
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#4049 Fix `parent` field occasionally missing in `/api/v1/project/{uuid}` responses
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#3948 Fix vex export returning invalid CycloneDX
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect

#4055 Bump Temurin base image to `21.0.4_7`
  src/main/docker/Dockerfile
Labels: dependencies, docker

#4056 Backport: Bump Temurin base image to `21.0.4_7`
  src/main/docker/Dockerfile
Labels: dependencies, docker

#4057 Bump bundled frontend to v4.11.6
  pom.xml
Labels: dependencies

#4058 Bump bundled frontend to v4.11.6
  pom.xml
Labels: dependencies

#4054 Backport: Fix vex export returning invalid CycloneDX
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect

#4045 Add changelog for v4.11.6
  docs/_posts/2024-08-10-v4.11.6.md
Labels: documentation

#4071 Fix `directDependencies`, `externalReferences`, `metadata` missing from `/api/v1/project/{uuid}` response when not already cached
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectMetadata.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4073 Bump bundled frontend to 4.11.7
  pom.xml
Labels: dependencies

#4075 Bump Alpine to 3.0.1
  pom.xml
Labels: dependencies, java

#3983 Add option to test notification publisher
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: enhancement

#3969 Add support for authors field
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue3936-author.json
  src/test/resources/unit/bom-issue3936-authors.json
  src/test/resources/unit/bom-issue3936-both.json
  src/test/resources/unit/cyclonedx/valid-bom-1.6.json
Labels: enhancement

#4104 Bump DataNucleus to 6.0.8
  pom.xml
Labels: dependencies, java

#4106 Disable H2 shutdown hook
  src/main/resources/application.properties
Labels: enhancement

#4107 Ensure URL-encoding of repository URL path segments
  src/main/java/org/dependencytrack/tasks/repositories/CargoMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/CpanMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/GemMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/GoModulesMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/HexMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/PypiMetaAnalyzer.java
Labels: defect

#4108 Fix project being rendered as PURL in email notifications
  src/main/resources/templates/notification/publisher/email.peb
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: defect
