Repository DependencyTrack/dependency-track, pull requests merged in 2024-07, with the labels that each got.

#3899 docs: add docs for base_path
  docs/_docs/getting-started/configuration.md
Labels: documentation

#3915 Set license name instead of ID when using custom license
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#3924 Add REST endpoints to tag and untag policies in bulk
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement

#3940 Backport: Bump io.github.jeremylong:open-vulnerability-clients from 6.1.1 to 6.1.2
  pom.xml
Labels: dependencies, java

#3941 Backport: Fix `BOM_CONSUMED` and `BOM_PROCESSED` notifications being dispatched with wrong scope for BOM processing V2
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3943 Backport: Bump debian from `0200978` to `f8bbfa0`
  src/main/docker/Dockerfile
Labels: dependencies, docker

#3942 Backport: Set license name instead of ID when using custom license
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#3944 Bump `oauth2-oidc-sdk` from 10.15 to 11.13
  pom.xml
Labels: dependencies, java

#3945 Bump bundled frontend to 4.11.5
  pom.xml
Labels: dependencies

#3921 Add OIDC Documentation for OneLogin
  docs/_docs/getting-started/openidconnect-configuration.md
  docs/images/screenshots/onelogin-oidc-configuration.png
  docs/images/screenshots/onelogin-oidc-parameters-field-groups.png
  docs/images/screenshots/onelogin-oidc-parameters.png
  docs/images/screenshots/onelogin-oidc-sso.png
  docs/images/screenshots/onelogin-oidc.png
Labels: documentation

#3959 Add regression test for missing `parent` property in `/v1/project/{uuid}` response
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#3960 Fix missing `projectTags` parameter for `POST /v1/bom` endpoint
  src/main/java/org/dependencytrack/model/Tag.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#3982 Ensure no unique constraint violation for `ProjectMetadata`
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/tasks/CloneProjectTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3990 Log warning when dependency graph is missing the root node
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: enhancement

#3965 fix: fix anchors in changelog documentation
  docs/_layouts/default.html
  docs/_posts/2018-03-30-v3.0.2.md
  docs/_posts/2018-10-02-v3.2.2.md
  docs/_posts/2018-10-25-v3.3.0.md
  docs/_posts/2018-11-13-v3.3.1.md
  docs/_posts/2018-12-22-v3.4.0.md
  docs/_posts/2019-04-16-v3.4.1.md
  docs/_posts/2019-06-07-v3.5.0.md
  docs/_posts/2019-07-17-v3.5.1.md
  docs/_posts/2019-09-28-v3.6.0.md
  docs/_posts/2019-10-01-v3.6.1.md
  docs/_posts/2019-12-16-v3.7.0.md
  docs/_posts/2020-01-07-v3.7.1.md
  docs/_posts/2020-03-22-v3.8.0.md
  docs/_posts/2021-01-03-v4.0.0.md
  docs/_posts/2021-01-12-v4.0.1.md
  docs/_posts/2021-02-09-v4.1.0.md
  docs/_posts/2021-03-17-v4.2.0.md
  docs/_posts/2021-03-20-v4.2.1.md
  docs/_posts/2021-05-07-v4.2.2.md
  docs/_posts/2021-08-02-v4.3.0.md
  docs/_posts/2021-08-03-v4.3.1.md
  docs/_posts/2021-08-07-v4.3.2.md
  docs/_posts/2021-08-20-v4.3.3.md
  docs/_posts/2021-08-31-v4.3.4.md
  docs/_posts/2021-09-20-v4.3.5.md
  docs/_posts/2021-09-20-v4.3.6.md
  docs/_posts/2022-02-17-v4.4.0.md
  docs/_posts/2022-02-18-v4.4.1.md
  docs/_posts/2022-03-04-v4.4.2.md
  docs/_posts/2022-05-18-v4.5.0.md
  docs/_posts/2022-10-11-v4.6.0.md
  docs/_posts/2022-10-13-v4.6.1.md
  docs/_posts/2022-10-24-v4.6.2.md
  docs/_posts/2022-11-18-v4.6.3.md
  docs/_posts/2022-12-16-v4.7.0.md
  docs/_posts/2023-01-31-v4.7.1.md
  docs/_posts/2023-04-18-v4.8.0.md
  docs/_posts/2023-05-16-v4.8.1.md
  docs/_posts/2023-05-17-v4.8.2.md
  docs/_posts/2023-10-16-v4.9.0.md
  docs/_posts/2023-10-30-v4.9.1.md
  docs/_posts/2023-12-08-v4.10.0.md
  docs/_posts/2023-12-19-v4.10.1.md
  docs/_posts/2024-05-07-v4.11.0.md
  docs/_posts/2024-05-19-v4.11.1.md
  docs/_posts/2024-06-01-v4.11.2.md
  docs/_posts/2024-06-03-v4.11.3.md
  docs/_posts/2024-06-24-v4.11.4.md
  docs/_posts/2024-07-08-v4.11.5.md
Labels: documentation

#4020 Fix validation error when XML BOM declares multiple namespaces
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/resources/unit/bom-issue4008.xml
Labels: defect

#4022 added missing endpoints in index html for open api upgrade
  src/main/webapp/index.html
Labels: defect, api docs

#4023 Handle breaking change in Trivy v0.54.0 server API
  src/main/java/org/dependencytrack/parser/trivy/model/Options.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect, integration/trivy
