Repository DependencyTrack/dependency-track, pull requests merged in 2024-11, with the labels that each got.

#4350 Fix incorrect CWE schema in OpenAPI spec
  src/main/java/org/dependencytrack/model/Vulnerability.java
Labels: defect, api docs, backport/4.12.2

#4306 Fix component hash policy evaluator
  src/main/java/org/dependencytrack/policy/ComponentHashPolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java
Labels: defect

#4369 Fix NullPointerException when fetching findings
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
Labels: defect, backport/4.12.2

#4374 Fix policy evaluation not happening upon creation or update of individual components
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/tasks/PolicyEvaluationTaskTest.java
Labels: defect, backport/4.12.2

#4377 Backport: Reduce memory usage of metrics update tasks
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Labels: enhancement

#4378 Backport: Fix CPE matching for NVD mirroring via REST API
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
  src/test/resources/unit/nvd/api/jsons/cve-2024-23113.json
Labels: defect

#4379 Backport: Fix incorrect CWE schema in OpenAPI spec
  src/main/java/org/dependencytrack/model/Vulnerability.java
Labels: defect

#4380 Backport: Fix NullPointerException when fetching findings
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
Labels: defect

#4381 Backport: Fix policy evaluation not happening upon creation or update of individual components
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/tasks/PolicyEvaluationTaskTest.java
Labels: defect

#4382 Backport: Fix nullable metrics fields having getters of primitive type
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
Labels: defect

#4394 Fix Trivy analyzer vulnerability matching for Go packages
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy, backport/4.12.2

#4395 Backport: Fix Trivy analyzer vulnerability matching for Go packages
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy

#4409 Add cyclonedx json media type when exporting components
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
Labels: defect, backport/4.12.2

#4414 Fix NPE when cloning projects with broken dependency graph
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, backport/4.12.2

#4415 Fix `project.active` being nullable
  dev/docker-compose.mysql.yml
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectVersion.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/search/ComponentIndexer.java
  src/main/java/org/dependencytrack/search/ProjectIndexer.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4122/v4122Updater.java
  src/test/java/org/dependencytrack/model/ProjectTest.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, backport/4.12.2

#4401 Move GHAM notification logic outside recursion
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
Labels: defect, integration/github, backport/4.12.2

#4417 Backport: Move GHSA notification logic outside recursion
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
Labels: defect

#4420 Backport: Add cyclonedx json media type when exporting components
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
Labels: defect

#4419 Backport: Fix NPE when cloning projects with broken dependency graph
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4418 Backport: Fix `project.active` being nullable
  dev/docker-compose.mysql.yml
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectVersion.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/search/ComponentIndexer.java
  src/main/java/org/dependencytrack/search/ProjectIndexer.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4122/v4122Updater.java
  src/test/java/org/dependencytrack/model/ProjectTest.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4421 Fix broken pagination in `/api/v1/cwe` endpoint
  src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: defect, backport/4.12.2
