Repository DependencyTrack/dependency-track, pull requests merged in 2024-09, with the labels that each got.

#4109 Support inclusion/exclusion of projects from BOM validation with tags
  pom.xml
  src/main/java/org/dependencytrack/model/BomValidationMode.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#4111 Update changelog for v4.12.0 with recent changes
  docs/_posts/2024-xx-xx-v4.12.0.md
Labels: documentation

#4116 Migrate Trivy integration to use Protobuf instead of JSON
  docs/_posts/2024-xx-xx-v4.12.0.md
  pom.xml
  src/main/java/org/dependencytrack/parser/trivy/TrivyParser.java
  src/main/java/org/dependencytrack/parser/trivy/model/Application.java
  src/main/java/org/dependencytrack/parser/trivy/model/BlobInfo.java
  src/main/java/org/dependencytrack/parser/trivy/model/CVSS.java
  src/main/java/org/dependencytrack/parser/trivy/model/DataSource.java
  src/main/java/org/dependencytrack/parser/trivy/model/DeleteRequest.java
  src/main/java/org/dependencytrack/parser/trivy/model/Layer.java
  src/main/java/org/dependencytrack/parser/trivy/model/OS.java
  src/main/java/org/dependencytrack/parser/trivy/model/Options.java
  src/main/java/org/dependencytrack/parser/trivy/model/Package.java
  src/main/java/org/dependencytrack/parser/trivy/model/PackageInfo.java
  src/main/java/org/dependencytrack/parser/trivy/model/PutRequest.java
  src/main/java/org/dependencytrack/parser/trivy/model/Result.java
  src/main/java/org/dependencytrack/parser/trivy/model/ScanRequest.java
  src/main/java/org/dependencytrack/parser/trivy/model/TrivyResponse.java
  src/main/java/org/dependencytrack/parser/trivy/model/Vulnerability.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/main/proto/trivy/cache/v1/service.proto
  src/main/proto/trivy/common/service.proto
  src/main/proto/trivy/scanner/v1/service.proto
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: enhancement, integration/trivy

#4110 Bump generated BOM to CycloneDX v1.5; Add external references
  .github/workflows/_meta-build.yaml
  pom.xml
  src/main/resources/services.bom.json
Labels: enhancement

#4134 Bump Alpine to 3.1.0 and adopt new framework features
  pom.xml
  src/main/docker/logback-json.xml
  src/main/docker/logback.xml
  src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
  src/main/webapp/WEB-INF/jetty-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#4131 Feat/customizable login page
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
Labels: enhancement

#4143 Add `AUTHOR` -> `AUTHORS` migration
  dev/docker-compose.mssql.yml
  src/main/java/org/dependencytrack/upgrade/v4120/v4120Updater.java
Labels: enhancement

#4146 Handle empty component and service names
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#4147 Handle existing duplicate component properties
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#4136 Feat/systemwide language
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
Labels: enhancement

#4154 Include team name in audit trail for API-submitted audit changes
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
Labels: enhancement

#4165 Fix infinite recursion during policy condition serialization
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/test/java/org/dependencytrack/resources/v1/PolicyConditionResourceTest.java
Labels: defect

#4141 Feat: Fix that Emails render all symbols right
  src/main/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishers.java
  src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/DefaultNotificationPublishersTest.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: defect

#3544 Global Audit View: Policy Violations
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
Labels: enhancement

#4093 Feat/add team selection in create project button
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement

#4171 Fix `directDependencies` of cloned projects referring to original component UUIDs
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4177 Visible Endpoint returns only Visible Teams(name, uuid)
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/VisibleTeams.java
Labels: defect

#4181 Cache Trivy DB for integration tests
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect

#4185 Fix breaking change in `PUT /api/v1/project` endpoint
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4187 Bump various dependencies
  pom.xml
Labels: dependencies

#4059 Enhance badge API to require authorization
  docs/_docs/integrations/badges.md
  src/main/java/org/dependencytrack/auth/Permissions.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/resources/openapi-configuration.yaml
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/auth/PermissionsTest.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
Labels: enhancement

#3468 Exclude pre-releases from NuGet latest version check
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Labels: enhancement

#4178 Fix missing parenthesis in documentation
  docs/_docs/best-practices.md
Labels: documentation

#4195 Fix metrics endpoint API docs erroneously claiming to return project and component data
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
Labels: defect, api docs

#4194 Ensure modifying project endpoints are transactional
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement
