Repository DependencyTrack/dependency-track, pull requests merged in 2024-12, with the labels that each got.

#4433 Bump Alpine to 3.1.2
  pom.xml
Labels: dependencies, backport/4.12.2

#4436 Backport: Bump Alpine to 3.1.2
  pom.xml
Labels: dependencies

#4423 Update Azure DevOps Extension
  docs/_docs/integrations/community-integrations.md
Labels: documentation

#4440 Bump bundled frontend to 4.12.2
  pom.xml
Labels: dependencies, backport/4.12.2

#4441 Backport: Bump bundled frontend to 4.12.2
  pom.xml
Labels: dependencies

#4442 Fix incompatibility of swagger-core with newer jackson-databind versions
  pom.xml
Labels: defect

#4439 Add changelog for v4.12.2
  docs/_posts/2024-12-04-v4.12.2.md
Labels: documentation

#4456 Fix notification tests not working for Jira
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: defect, backport/4.12.3

#4458 Fix component de-duplication potentially causing duplicate dependency graph entries
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue4455.json
Labels: defect, backport/4.12.3

#4459 Backport: Fix broken pagination in `/api/v1/cwe` endpoint
  src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: defect

#4460 Backport: Fix notification tests not working for Jira
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: defect

#4461 Backport: Fix component de-duplication potentially causing duplicate dependency graph entries
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue4455.json
Labels: defect

#4383 Add /v1/project/batchDelete API method that deletes with SQL
  src/main/java/org/dependencytrack/exception/ProjectOperationException.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/exception/ProjectOperationExceptionMapper.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProjectOperationProblemDetails.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#4472 Update DEVELOPING.md with command for single unit-test
  DEVELOPING.md
Labels: documentation

#4480 Fix component SWID tag ID not being considered in project cloning
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, backport/4.12.3

#4481 Backport: Fix component SWID tag ID not being considered in project cloning
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4486 Reduce database round-trips during BOM processing
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentIdentity.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: enhancement

#4470 Compose Metadata Analyzer: Refactor to support V2 and V1 repositories
  src/main/java/org/dependencytrack/tasks/repositories/AbstractMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/util/ComponentVersion.java
  src/main/java/org/dependencytrack/util/JsonUtil.java
  src/test/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzerTest.java
  src/test/resources/unit/tasks/repositories/https---composer.available.com-io-captain-hook.json
  src/test/resources/unit/tasks/repositories/https---composer.available.com-packages.json
  src/test/resources/unit/tasks/repositories/https---composer.available.com.matches-io-captain-hook.json
  src/test/resources/unit/tasks/repositories/https---composer.available.com.matches-packages.json
  src/test/resources/unit/tasks/repositories/https---composer.dummy.com.therepo-packages.json
  src/test/resources/unit/tasks/repositories/https---composer.include.com.metadata-packages.json
  src/test/resources/unit/tasks/repositories/https---composer.include.com.metadata-space-cowboy.json
  src/test/resources/unit/tasks/repositories/https---composer.include.com.userpass-packages.json
  src/test/resources/unit/tasks/repositories/https---composer.include.com.userpass-space-cowboy.json
  src/test/resources/unit/tasks/repositories/https---packages.drupal.org-drupal-mollie.json
  src/test/resources/unit/tasks/repositories/https---packages.drupal.org-packages.json
  src/test/resources/unit/tasks/repositories/https---repo.empty.org-packages.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org-p-magento-adobe-ims.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org-p-typo3-class-alias-loader.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org-packages.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org-typo3-class-alias-loader.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org.v1-magento-adobe-ims.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org.v1-monolog-monolog.json
  src/test/resources/unit/tasks/repositories/https---repo.packagist.org.v1-packages.json
Labels: enhancement, backport/4.12.3

#4501 Docs: Mention Flashpoint as new owner of Vulndb
  docs/_docs/datasources/vulndb.md
Labels: documentation
