Repository DependencyTrack/dependency-track, pull requests merged in 2024-03, with the labels that each got.

#3517 Upload test coverage for PRs via separate workflow
  .github/workflows/ci-test-pr-coverage.yml
  .github/workflows/ci-test.yaml
Labels: ci

#3515 Bump Alpine to `2.2.5`
  pom.xml
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: dependencies, java

#3512 Fix type of `purl` fields in Swagger docs
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/Project.java
Labels: defect, api docs

#3531 Update changelog for v4.11.0
  docs/_posts/2024-xx-xx-v4.11.0.md
Labels: documentation

#3536 Clarify OpenID Connect group mapping to teams
  docs/_docs/getting-started/openidconnect-configuration.md
  docs/_posts/2024-xx-xx-v4.11.0.md
Labels: documentation

#3522 Validate uploaded BOMs against CycloneDX schema
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/InvalidBomException.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/InvalidBomProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/resources/unit/bom-1.xml
Labels: enhancement

#3537 Add endpoint for updating API key comment
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement

#3555 Perform License Resolution On Name Field During SBOM Import
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3557 OpenAPI spec fixes and improvements
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/SearchResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/test/java/org/dependencytrack/resources/v1/IntegrationResourceTest.java
Labels: defect, enhancement, api docs

#3556 Update License Of Existing Components On BOM Upload
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect

#3558 Provide meaningful error message for `bom` and `vex` exceeding Jackson's character limit
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/exception/JsonMappingExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect

#3559 Fix unhandled `NotFoundException`s causing a `HTTP 500` response
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/resources/v1/exception/NotFoundExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/exception/NotFoundExceptionMapperTest.java
Labels: defect

#3560 Extend length of `PURL` and `PURLCOORDINATES` columns from 255 to 786
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentAnalysisCache.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/upgrade/v4110/v4110Updater.java
Labels: defect

#3574 Disable automatic API key generation for teams. Fixes part of issue #2552.
  docs/_docs/integrations/rest-api.md
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement

#3561 Generate SARIF File Of Project Vulnerability Findings
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/resources/templates/findings/sarif.peb
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#3590 Validate UUID request parameters
  src/main/java/org/dependencytrack/model/validation/ValidUuid.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/exception/ConstraintViolationExceptionMapper.java
  src/main/java/org/dependencytrack/resources/v1/exception/JsonMappingExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/exception/ConstraintViolationExceptionMapperTest.java
Labels: defect, api docs
