Repository DependencyTrack/dependency-track, pull requests merged in 2024-04, with the labels that each got.

#3597 Normalize capitalization of PyPI
  README.md
  docs/_docs/datasources/repositories.md
  docs/_posts/2018-12-22-v3.4.0.md
  docs/index.md
  docs/odt-odc-comparison.html
Labels: documentation

#3588 New feature: VulnDB Aliases!
  src/main/java/org/dependencytrack/parser/vulndb/ModelConverter.java
  src/main/java/org/dependencytrack/parser/vulndb/VulnDbParser.java
  src/main/java/org/dependencytrack/parser/vulndb/model/CvssV2Metric.java
  src/main/java/org/dependencytrack/parser/vulndb/model/CvssV3Metric.java
  src/main/java/org/dependencytrack/util/VulnerabilityUtil.java
  src/test/java/org/dependencytrack/parser/vulndb/ModelConverterTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityUtilTest.java
  src/test/resources/unit/vulndb.jsons/vulnerabilities_0.json
Labels: enhancement, integration/vulndb

#3604 Advertise official Helm chart in docs
  README.md
  docs/_docs/getting-started/configuration.md
  docs/_docs/getting-started/data-directory.md
  docs/_docs/getting-started/database-support.md
  docs/_docs/getting-started/deploy-exewar.md
  docs/_docs/getting-started/deploy-kubernetes.md
  docs/_docs/getting-started/initial-startup.md
  docs/_docs/getting-started/internal-ca.md
  docs/_docs/getting-started/ldap-configuration.md
  docs/_docs/getting-started/monitoring.md
  docs/_docs/getting-started/openidconnect-configuration.md
  docs/_docs/getting-started/recurring-tasks.md
Labels: documentation

#3595 Vuln db severity
  src/main/java/org/dependencytrack/parser/vulndb/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
Labels: defect, integration/vulndb

#3549 Implement the hackage and nixpkgs meta analyzers
  .gitignore
  pom.xml
  src/main/java/org/dependencytrack/model/RepositoryType.java
  src/main/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/IMetaAnalyzer.java
  src/main/java/org/dependencytrack/tasks/repositories/NixpkgsMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/HackageMetaAnalyzerTest.java
  src/test/java/org/dependencytrack/tasks/repositories/NixpkgsMetaAnalyzerTest.java
Labels: enhancement

#3618 Update changelog for v4.11 with recent changes
  docs/_posts/2024-xx-xx-v4.11.0.md
Labels: documentation

#3499 Add support for component properties
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentProperty.java
  src/main/java/org/dependencytrack/model/validation/EnumValue.java
  src/main/java/org/dependencytrack/model/validation/EnumValueValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/main/resources/META-INF/persistence.xml
  src/test/java/org/dependencytrack/model/ComponentPropertyTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentPropertyResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
  src/test/resources/unit/bom-1.xml
Labels: enhancement

#3535 Improve Lucene observability
  docs/_docs/getting-started/monitoring.md
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/search/ComponentIndexer.java
  src/main/java/org/dependencytrack/search/IndexManager.java
  src/main/java/org/dependencytrack/search/IndexManagerFactory.java
  src/main/java/org/dependencytrack/search/LicenseIndexer.java
  src/main/java/org/dependencytrack/search/LoggingInfoStream.java
  src/main/java/org/dependencytrack/search/ObjectIndexer.java
  src/main/java/org/dependencytrack/search/ProjectIndexer.java
  src/main/java/org/dependencytrack/search/ServiceComponentIndexer.java
  src/main/java/org/dependencytrack/search/VulnerabilityIndexer.java
  src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java
  src/main/java/org/dependencytrack/tasks/IndexTask.java
Labels: enhancement

#3625 Include pagination parameters in OpenAPI spec
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/CweResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
Labels: enhancement, api docs

#3630 Trivy tweaks
  dev/docker-compose.trivy.yml
  docs/_docs/datasources/trivy.md
  docs/_posts/2024-xx-xx-v4.11.0.md
  docs/images/screenshots/trivy-configuration.png
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
Labels: documentation, integration/trivy

#3631 Include sorting query parameters in OpenAPI spec
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
Labels: enhancement, api docs

#3621 support for experimental configurations
  docs/_posts/2024-xx-xx-v4.11.0.md
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTaskV2.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#3650 Fix `JDOFatalUserException` for long reference URLs from OSS Index
  src/main/java/org/dependencytrack/model/FindingAttribution.java
  src/test/java/org/dependencytrack/model/FindingAttributionTest.java
Labels: defect

#3648 Gracefully handle unique constraint violations
  src/main/java/org/dependencytrack/tasks/repositories/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
Labels: enhancement

#3652 Bump Temurin base image to `21.0.3_9`
  src/main/docker/Dockerfile
Labels: dependencies, docker

#3657 Add support for worker pool drain timeout
  docs/_docs/getting-started/configuration.md
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/notification/NotificationSubsystemInitializer.java
  src/main/resources/application.properties
Labels: enhancement

#3658 Update v4.11 changelog with recent changes
  docs/_posts/2024-xx-xx-v4.11.0.md
Labels: documentation
