Repository DependencyTrack/dependency-track, pull requests merged in 2025-06, with the labels that each got.

#4876 docs: More specific description of BOM upload
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
Labels: enhancement, api docs

#5032 Add AWS Cognito configuration example
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation, backport/4.13.3

#5034 Add apiserver health check to Compose files
  dev/docker-compose.yml
  src/main/docker/docker-compose.yml
Labels: defect, backport/4.13.3

#5033 Handle dangling SPDX expression operators
  src/main/java/org/dependencytrack/model/validation/SpdxExpressionValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
  src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
  src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java
Labels: defect, backport/4.13.3

#5058 Remove system requirements check; Lower resource requirements
  .idea/runConfigurations/Jetty.run.xml
  docs/_docs/getting-started/deploy-docker.md
  docs/_docs/getting-started/deploy-exewar.md
  src/main/java/org/dependencytrack/RequirementsVerifier.java
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/exception/RequirementsException.java
  src/main/java/org/dependencytrack/notification/NotificationSubsystemInitializer.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/search/IndexSubsystemInitializer.java
  src/main/java/org/dependencytrack/upgrade/UpgradeInitializer.java
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#5061 Add whitespace sanitization in fuzzySearch CPE to fix CPE validation errors
  src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
Labels: defect, backport/4.13.3
