Repository DependencyTrack/dependency-track, pull requests merged in 2025-02, with the labels that each got.

#4610 Fix false negatives in CPE matching for ANY and NA versions
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Labels: defect, backport/4.12.4

#4612 Backport: Fix false negatives in CPE matching for ANY and NA versions
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Labels: defect

#4624 Refactor `VulnerabilityManagementUploadTask` to be more efficient
  src/main/java/org/dependencytrack/integrations/kenna/KennaSecurityUploader.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityManagementUploadTask.java
  src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploaderTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/DefectDojoUploadTaskTest.java
  src/test/java/org/dependencytrack/tasks/KennaSecurityUploadTaskTest.java
Labels: defect, backport/4.12.4

#4626 Backport: Refactor `VulnerabilityManagementUploadTask` to be more efficient
  src/main/java/org/dependencytrack/integrations/kenna/KennaSecurityUploader.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityManagementUploadTask.java
  src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploaderTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/DefectDojoUploadTaskTest.java
  src/test/java/org/dependencytrack/tasks/KennaSecurityUploadTaskTest.java
Labels: defect

#4627 Bump Temurin base image to 21.0.6_7
  src/main/docker/Dockerfile
Labels: dependencies, backport/4.12.4

#4628 Backport: Bump Temurin base image to 21.0.6_7
  src/main/docker/Dockerfile
Labels: dependencies

#4629 Backport: Fix erroneous URL-encoding of the Maven groupId
  src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzerTest.java
Labels: defect

#4566 Bump alpine from 3.1.2 to 3.2.0
  docs/_docs/integrations/rest-api.md
  docs/images/screenshots/new-apiKey.png
  docs/images/screenshots/teams.png
  pom.xml
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4130/v4130Updater.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/OidcResourceAuthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: enhancement

#4636 Handle invalid CVSS vectors and processing failures for OSV
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
Labels: defect, integration/osv, backport/4.12.4

#4638 Backport: Handle invalid CVSS vectors and processing failures for OSV
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
Labels: defect, integration/osv

#4641 Backport: Bump bundled frontend to 4.12.4
  pom.xml
Labels: dependencies

#4630 Add changelog for v4.12.4
  docs/_posts/2025-02-10-v4.12.4.md
Labels: documentation

#4656 Backport: Bump io.github.jeremylong:open-vulnerability-clients from 7.2.1 to 7.2.2
  pom.xml
Labels: dependencies

#4658 Bump bundled frontend to 4.12.5
  pom.xml
Labels: dependencies, backport/4.12.5

#4659 Backport: Bump bundled frontend to 4.12.5
  pom.xml
Labels: dependencies

#4657 Add changelog for v4.12.5
  docs/_posts/2025-02-17-v4.12.5.md
Labels: documentation

#4669 Bump net.minidev:json-smart to 2.5.2
  pom.xml
Labels: dependencies, backport/4.12.6

#4670 Analyze all components of a project at once instead of in batches
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
Labels: defect, integration/trivy, backport/4.12.6

#4671 Backport: Fix possible NPEs in TrivyAnalysisTask
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy

#4672 Backport: Bump net.minidev:json-smart to 2.5.2
  pom.xml
Labels: dependencies

#4673 Backport: Analyze all components of a project at once instead of in batches
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
Labels: defect, integration/trivy

#4674 chore: fix typos in properties file
  src/main/resources/application.properties
Labels: documentation

#4679 Fix notification webhook sending blank headers
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
Labels: defect, backport/4.12.6

#4680 Backport: Fix notification webhook sending blank header
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
Labels: defect

#4684 Disable `include` tag for Pebble templates
  pom.xml
  src/main/java/org/dependencytrack/notification/publisher/AbstractWebhookPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/ConsolePublisher.java
  src/main/java/org/dependencytrack/notification/publisher/CsWebexPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/JiraPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MattermostPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/MsTeamsPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/SendMailPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/SlackPublisher.java
  src/main/java/org/dependencytrack/notification/publisher/WebhookPublisher.java
  src/test/java/org/dependencytrack/notification/publisher/AbstractPublisherTest.java
  src/test/java/org/dependencytrack/notification/publisher/SendMailPublisherTest.java
Labels: defect, backport/4.12.6

#4691 Add changelog for v4.12.6
  docs/_posts/2025-02-24-v4.12.6.md
Labels: documentation

#4651 Implement basic telemetry collection
  dev/docker-compose.yml
  docs/_docs/getting-started/telemetry.md
  docs/images/screenshots/telemetry.png
  pom.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/TelemetrySubmissionEvent.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/TelemetrySubmissionTask.java
  src/main/resources/application.properties
  src/main/resources/services.bom.json
  src/test/java/org/dependencytrack/tasks/TelemetrySubmissionTaskTest.java
Labels: enhancement
