Repository DependencyTrack/dependency-track, pull requests merged in 2025-01, with the labels that each got.

#4511 Fix onlyOutdated ungrouped component filtering
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: defect, backport/4.12.3

#4504 Component Analyse Cache: make description more clear
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
Labels: documentation

#4502 Postpone deprecation of unauthenticated access to Badge API
  docs/_docs/integrations/badges.md
Labels: documentation

#4541 Fix REST endpoints for adding tags
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: defect, backport/4.12.3

#4543 Backport: Fix REST endpoints for adding tags
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: defect

#4544 Recreate outdated check constraints for `CLASSIFIER` columns
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4123/v4123Updater.java
Labels: defect, backport/4.12.3

#4545 Recreate outdated check constraints for `CLASSIFIER` columns
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4123/v4123Updater.java
Labels: defect

#4546 composer meta analyzer: add DEBUG logging
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
Labels: enhancement

#4556 docs: Clarify OpenAPI endpoint location
  docs/_docs/integrations/rest-api.md
Labels: documentation

#4547 Fix miscellaneous typos
  docs/_docs/integrations/badges.md
  docs/_docs/usage/cicd.md
  docs/_docs/usage/collection-projects.md
Labels: documentation

#4576 Update quickstart Compose file to use Postgres instead of H2
  dev/docker-compose.postgres.yml
  src/main/docker/docker-compose.yml
Labels: enhancement

#4580 Add SecObserve to community integrations
  docs/_docs/integrations/community-integrations.md
Labels: documentation

#4578 Handle GitHub GraphQL API rate limiting
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/github/ModelConverter.java
  src/main/java/org/dependencytrack/parser/github/graphql/GitHubSecurityAdvisoryParser.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/GitHubSecurityAdvisory.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/GitHubVulnerability.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/PageableList.java
  src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/resources/templates/github/securityAdvisories.peb
  src/test/java/org/dependencytrack/parser/github/GitHubSecurityAdvisoryParserTest.java
  src/test/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTaskTest.java
Labels: defect, backport/4.12.3

#4581 Backport: Handle GitHub GraphQL API rate limiting
  pom.xml
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/github/ModelConverter.java
  src/main/java/org/dependencytrack/parser/github/graphql/GitHubSecurityAdvisoryParser.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/GitHubSecurityAdvisory.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/GitHubVulnerability.java
  src/main/java/org/dependencytrack/parser/github/graphql/model/PageableList.java
  src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/resources/templates/github/securityAdvisories.peb
  src/test/java/org/dependencytrack/parser/github/GitHubSecurityAdvisoryParserTest.java
  src/test/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTaskTest.java
Labels: defect

#4582 Bump Debian and Temurin base images to latest digest
  src/main/docker/Dockerfile
Labels: dependencies

#4588 Bump bundled frontend to 4.12.3
  pom.xml
Labels: dependencies, backport/4.12.3

#4589 Backport: Bump bundled frontend to 4.12.3
  pom.xml
Labels: dependencies

#4583 Add changelog for v4.12.3
  docs/_posts/2025-01-27-v4.12.3.md
Labels: documentation

#4594 Fix possible NPEs during tag binding
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, backport/4.12.4

#4595 Backport: Fix possible NPEs during tag binding
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4602 Fix erroneous URL-encoding of the Maven groupId
  src/main/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/MavenMetaAnalyzerTest.java
Labels: defect, backport/4.12.4
