Repository DependencyTrack/dependency-track, pull requests merged in 2025-03, with the labels that each got.

#4715 Add support for Snyk API version 2024-10-15
  src/main/java/org/dependencytrack/parser/snyk/SnykParser.java
  src/test/java/org/dependencytrack/parser/snyk/SnykParserTest.java
  src/test/resources/unit/snyk.jsons/ranges.json
Labels: enhancement, integration/snyk

#4732 Fix NPE during NVD mirroring via REST API when encountering invalid CPEs
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
Labels: defect, integration/nvd, backport/4.12.7

#4734 Backport: Fix NPE during NVD mirroring via REST API when encountering invalid CPEs
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
Labels: defect, integration/nvd

#4735 Remove erroneous client-side caching in Trivy analyzer
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect, integration/trivy, backport/4.12.7

#4733 Fix notification limiting to tags not working reliably
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: defect, backport/4.12.7

#4736 Backport: Remove erroneous client-side caching in Trivy analyzer
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskTest.java
Labels: defect, integration/trivy

#4737 Backport: Fix notification limiting to tags not working reliably
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/notification/NotificationRouter.java
  src/test/java/org/dependencytrack/notification/NotificationRouterTest.java
Labels: defect

#4738 Fix tags from BOM upload request not being applied for existing projects
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect, backport/4.12.7

#4740 Backport: Fix tags from BOM upload request not being applied for existing projects
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#4745 Fix component properties not being cloned
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, backport/4.12.7

#4746 Backport: Fix component properties not being cloned
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#4642 #4620 add "lastVulnerabilityAnalysis" to project
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
Labels: enhancement

#4752 Bump bundled frontend to 4.12.7
  pom.xml
Labels: dependencies, backport/4.12.7

#4753 Backport: Bump bundled frontend to 4.12.7
  pom.xml
Labels: dependencies

#4751 Add changelog for v4.12.7
  docs/_posts/2025-03-12-v4.12.7.md
Labels: documentation

#4767 handle corner case if no vulnerabilities have compatible aliases
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
Labels: defect

#4766 add endpoint to mass-create tags
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement

#4796 Add feature to define the test title for DefectDojo integration
  docs/_docs/integrations/defectdojo.md
  docs/images/screenshots/defectdojo_test-title.png
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
  src/test/java/org/dependencytrack/tasks/DefectDojoUploadTaskTest.java
Labels: enhancement, integration/defectdojo

#4778 docs: Update Azure AD configuration to Entra ID
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation
