Repository DependencyTrack/dependency-track, pull requests merged in 2025-08, with the labels that each got.

#5168 Backport: Fix OSV ubuntu advisory containing severity without type
  src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java
  src/test/java/org/dependencytrack/parser/osv/OsvAdvisoryParserTest.java
  src/test/java/org/dependencytrack/tasks/OsvDownloadTaskTest.java
  src/test/resources/unit/osv.jsons/osv-UBUNTU-CVE-2025-6297.json
Labels: defect

#5169 Backport: bump org.apache.commons:commons-compress
  pom.xml
  src/main/java/org/dependencytrack/util/CompressUtil.java
Labels: dependencies

#5172 Backport: Add AWS Cognito configuration example
  docs/_docs/getting-started/openidconnect-configuration.md
Labels: documentation

#5173 Backport: Handle dangling SPDX expression operators
  src/main/java/org/dependencytrack/model/validation/SpdxExpressionValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
  src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
  src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java
Labels: defect

#5178 Backport: Fix BOM export failing for projects of type NONE
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#5176 Backport: Add whitespace sanitization in fuzzySearch CPE to fix CPE validation errors
  src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
Labels: defect

#5175 Backport: Improve Composer meta analyzer's ability to deal with minified metadata
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzerTest.java
  src/test/resources/unit/tasks/repositories/https---composer.include.com.metadata-galaxy-cow-arrayentry.json
Labels: defect

#5183 Bump bundled frontend to 4.13.3
  pom.xml
Labels: dependencies

#5181 Bump Docker base images to latest digests
  src/main/docker/Dockerfile
Labels: dependencies

#5184 Backport: Bump bundled frontend to 4.13.3
  pom.xml
Labels: dependencies

#5160 Fix inverted component matching
  docs/_docs/FAQ.md
  src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java
Labels: defect

#5226 Migrate to NVD 2.0 data feeds
  docs/_docs/datasources/nvd.md
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2021_duplicate-cpes.json
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.json
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.meta
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2021_duplicate-cpes.json
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2022.json
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2022.meta
Labels: enhancement, backport/4.13.4

#5231 Fix failing TrivyAnalysisTaskIntegrationTest
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect

#5234 Backport: Handle URLs in composer package metadata pattern
  src/main/java/org/dependencytrack/tasks/repositories/ComposerMetaAnalyzer.java
Labels: defect

#5236 Backport: Migrate to NVD 2.0 data feeds
  docs/_docs/datasources/nvd.md
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2021_duplicate-cpes.json
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.json
  src/test/resources/unit/nvd/feed/nvdcve-1.1-2022.meta
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2021_duplicate-cpes.json
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2022.json
  src/test/resources/unit/nvd/feed/nvdcve-2.0-2022.meta
Labels: enhancement

#5238 Bump commons-lang3 to 3.18.0
  pom.xml
Labels: dependencies, backport/4.13.4

#5239 Bump Temurin base image to 21.0.8_9
  src/main/docker/Dockerfile
  src/main/docker/Dockerfile.alpine
Labels: dependencies, backport/4.13.4

#5240 Bump Debian base image to latest digest
  src/main/docker/Dockerfile
Labels: dependencies

#5242 Backport: Bump angus-mail to 2.0.4
  pom.xml
Labels: dependencies

#5248 Fix failing Trivy OS matching for distro versions with special characters
  src/main/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/scanners/TrivyAnalysisTaskIntegrationTest.java
Labels: defect, integration/trivy, backport/4.13.4

#5251 Add changelog for v4.13.4
  docs/_posts/2025-08-26-v4.13.4.md
Labels: documentation

#5264 fix null when NuGet package has only pre-released versions
  src/main/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/NugetMetaAnalyzerTest.java
Labels: defect, backport/4.13.5
