Repository DependencyTrack/dependency-track, pull requests merged in 2025-05, with the labels that each got.

#4907 Fix failing v4.13.1 migration for MSSQL deployments that pre-date v4.11.0
  src/main/java/org/dependencytrack/upgrade/v4131/TagDeduplicationPreUpgradeHook.java
  src/main/java/org/dependencytrack/upgrade/v4131/v4131Updater.java
Labels: defect, backport/4.13.2

#4912 Migrate to maintained protobuf-maven-plugin
  pom.xml
Labels: technical debt

#4910 Fix summary notifications not sent when "skip if unchanged" is enabled
  src/main/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTask.java
  src/test/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTaskTest.java
Labels: defect, backport/4.13.2

#4913 Backport: Fix summary notifications not sent when "skip if unchanged" is enabled
  src/main/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTask.java
  src/test/java/org/dependencytrack/tasks/ScheduledNotificationDispatchTaskTest.java
Labels: defect

#4930 Bump bundled frontend to 4.13.2
  pom.xml
Labels: dependencies, backport/4.13.2

#4931 Backport: Bump bundled frontend to 4.13.2
  pom.xml
Labels: dependencies

#4932 Add changelog for v4.13.2
  docs/_posts/2025-05-09-v4.13.2.md
Labels: documentation

#4935 Make POLICY_VIOLATION emails more informative
  src/main/resources/templates/notification/publisher/email.peb
Labels: enhancement

#4806 Add Metrics update trigger after cloning a project
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Labels: defect

#4857 handleRequestException: add baseUrl to log
  src/main/java/org/dependencytrack/tasks/repositories/AbstractMetaAnalyzer.java
Labels: enhancement

#4942 Classify GPL with CPE as weak copyleft
  src/main/resources/default-objects/licenseGroups.json
Labels: enhancement

#4949 Enable source filtering in SARIF format for /finding/project/{UUID}
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/resources/unit/sarif/expected-all.sarif.json
  src/test/resources/unit/sarif/expected-internal.sarif.json
Labels: defect

#4968 switch cvss handling to metaeffekt
  pom.xml
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/parser/github/ModelConverter.java
  src/main/java/org/dependencytrack/parser/nvd/NvdParser.java
  src/main/java/org/dependencytrack/parser/nvd/api20/ModelConverter.java
  src/main/java/org/dependencytrack/parser/osv/OsvAdvisoryParser.java
  src/main/java/org/dependencytrack/parser/vulndb/ModelConverter.java
  src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java
  src/main/java/org/dependencytrack/util/CvssUtil.java
  src/test/java/org/dependencytrack/parser/vulndb/ModelConverterTest.java
  src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
  src/test/java/org/dependencytrack/tasks/NistApiMirrorTaskTest.java
  src/test/java/org/dependencytrack/tasks/NistMirrorTaskTest.java
  src/test/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTaskTest.java
  src/test/java/org/dependencytrack/util/CvssUtilTest.java
Labels: enhancement
