Repository DependencyTrack/dependency-track, pull requests merged in 2025-09, with the labels that each got.

#5265 improve detection if version is commit sha or release tag for github purl
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Labels: defect, backport/4.13.5

#5275 Fix NullPointerException in GithubMetaAnalyzer when analyzing GitHub Actions
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
Labels: defect, backport/4.13.5

#5280 make CPE matching case-insensitive
  src/main/java/org/dependencytrack/model/VulnerableSoftware.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
  src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4135/v4135Updater.java
  src/test/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManagerTest.java
  src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Labels: defect, backport/4.13.5

#5299 Backport: Make CPE matching case-insensitive
  src/main/java/org/dependencytrack/model/VulnerableSoftware.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManager.java
  src/main/java/org/dependencytrack/search/VulnerableSoftwareIndexer.java
  src/main/java/org/dependencytrack/tasks/scanners/AbstractVulnerableSoftwareAnalysisTask.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v4135/v4135Updater.java
  src/test/java/org/dependencytrack/search/FuzzyVulnerableSoftwareSearchManagerTest.java
  src/test/java/org/dependencytrack/tasks/scanners/InternalAnalysisTaskCpeMatchingTest.java
Labels: defect

#5224 Add Support for CycloneDX Scope Data
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentIdentity.java
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/Scope.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/integrations/FindingPackagingFormatTest.java
  src/test/java/org/dependencytrack/model/FindingTest.java
Labels: enhancement

#5334 Bump container images to Java 25
  src/main/docker/Dockerfile
  src/main/docker/Dockerfile.alpine
Labels: dependencies, docker

#5352 Backport: Bump open-vulnerability-clients to 9.0.1
  pom.xml
Labels: dependencies

#5350 Backport: improve detection if version is commit sha or release tag for github purl
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
  src/test/java/org/dependencytrack/tasks/repositories/GitHubMetaAnalyzerTest.java
Labels: defect

#5353 Backport: only return tags directly associated with a policy
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: defect

#5355 Backport: Bump cyclonedx-core-java to 11.0.0
  pom.xml
Labels: dependencies

#5359 Backport: Fix NullPointerException in GithubMetaAnalyzer when analyzing GitHub Actions
  src/main/java/org/dependencytrack/tasks/repositories/GithubMetaAnalyzer.java
Labels: defect
